'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: go
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go-version }}'
        name: Test Go Standard
        uses: ./
        env:
            IMPORT: shikharvashistha/contentx
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        working-directory: src/cmd
        run: go run main.go